### ISSUE TITLE
Error: illegal character

### ISSUE THREAD

**Issue by gopher-confocal** [CellMoTher/AccPbFRET#1]
Hi, when I try to compile and run AccPbFRET_Plugin.java in ImageJ 1.53, I get a huge error message regarding an illegal character and illegal escape character. Can this be corrected, please? Thank you.
[Errors.txt](https://github.com/CellMoTher/AccPbFRET/files/7146647/Errors.txt)

**Comment by camlloyd** [comment]
Thank you @gopher-confocal! With the release of `v4.0.0`, it is no longer necessary to _Compile and Run_.

To install:
1. Download the latest version of [Fiji](https://fiji.sc/) (recommended).
2. Enable the FRET Imaging [update site](https://imagej.net/update-sites/following).
3. Once installed, go to _Plugins > FRET Imaging > AccPbFRET_.
